from ..nbt import NBTCompound, NBTInt, NBTList, NBTString

import json
from pathlib import Path

from typing import TypedDict, Literal


HERE = Path(__file__).parent.resolve()


class SkullData(TypedDict):
    npc: dict[
        Literal[
            'Steve',
            'Alex',
            'Assassin',
            'Split',
            'Pink Hair Boy',
            'Rainbow',
            'Iron Miner',
            'Floral',
            'Ripped Jeans',
            'Wood Creeper',
            'Ice Crystals',
            'Thick Jacket',
            'Nagisashiota',
            'Normal Girl',
            'Grim Reaper',
            'Rain Boots',
            'Plaid Shirt',
            'Yellow Shoes',
            'Night Girl',
            'Ghost Boy',
            'Bandana',
            'Moana',
            'Maroon 2',
            'Ocean Dusk',
            'Tough Teen',
            'Lavender',
            'Harambe',
            'Faded Winter',
            'Blue Scarf',
            'Christmas Girl',
            'Winter Dreams',
            'Girl #1',
            'Candy Pop',
            'Red Hoodie',
            'Hatsunemiku',
            'Teenager',
            'Blue Hoodie',
            'Blue Teenager',
            'Redstone Guy',
            'Bright Girl',
            'Santa',
            'Candy Girl',
            'Blue Girl',
            'Rainbow Girl',
            'Casual Girl',
            'Slime Girl',
            'Pony Girl',
            'Cupa',
            'Simply Plaid',
            'Bunny',
            'Stripped Hoodie',
            'Cool Boy',
            'Dj',
            'Gamer Boy',
            'Police Man',
            'Blonde Teenager',
            'Creeper Boy',
            'Parkour Teen',
            'Dino Girl',
            'Midkip Girl',
            'Pika Girl',
            'Black Hoodie',
            'Night Sky',
            'Bandit',
            'Butcher',
            'Cute Girl',
            'Modern Soldier',
            'Country Girl',
            'Minecraft Gamer',
            'Gamer Girl',
            'Scarf Boy',
            'Tigeronesie',
            'Foxylady',
            'Guymanuel',
            'Cool Hoodie',
            'Red Teen',
            'Black Jacket',
            'Ninjakid',
            'Griefer',
            'Surprised Dude',
            'Business Suit',
            'White Hoodie',
            'Dino Boy',
            'NFL Player',
            'Boy Hoodie',
            'Blue and White',
            'Astronaut',
            'Farmer',
            'Blueboy',
            'Abrahamlincoln 2',
            'Blue Stripes',
            'Abrahamlincoln',
            'Stardust',
            'Red Roses',
            'Cool Blue Guy',
            'Pink Tux',
            'Bio Hazard Suit',
            'Cool Gamer',
            'Fox Hoodie',
            'Chuck Norris',
            'Bat Girl',
            'Gray Hoodie',
            'Safety Miner',
            'Red Jumper',
            'Hungry Boy',
            'Pilot',
            'Zyro',
            'Winter Parkour',
            'Scientist',
            'Minecon Attendee',
            'Red Jacket',
            'Cowboy',
            'Nike Boy',
            'Skull Kid',
            'Pete',
            'Faded Teen',
            'Green Teen',
            'Orange Hoodie',
            'Martialartist',
            'Ombrebabe',
            'Free Runner',
            'Blondie',
            'Caveman',
            'Autumn',
            'Gangster',
            'Riotpolice',
            'Neilarmstrong',
            'Casualguy',
            'Winterwonderland',
            'Armyofficer',
            'Scottishsteve',
            'Lightbluehoodie',
            'Plaidboy',
            'Adventurer',
            'Darkhoodie',
            'Glasses',
            'Gameboyhoodie',
            'Tennisplayer',
            'Lumberjack',
            'Limehoodie',
            'Napoleon',
            'Scarf',
            'Skaterboy',
            'Vintageroses',
            'Animalhunter',
            'Eskimo',
            'Arnoldschwarzenegger',
            'Casualhoodie',
            'Alberteinstein',
            'Fox',
            'Chisaki',
            'Adventurersteve',
            'Hipsterguy',
            'Greenshirt',
            'Elevatorguy',
            'Blackandblue',
            'Goldenhoodie 2',
            'Goldenhoodie',
            'Snowsuit',
            'Monk',
            'Navycaptain',
            'Tuxedo',
            'Playfulcharm',
            'Diver',
            'Redscarf',
            'Yellowhoodie',
            'Cleopatra',
            'Romancitizen',
            'Maleadventurer',
            'Teenminer',
            'Redeyes',
            'Sportyboy',
            'Stripedteen',
            'Blondehair',
            'Arctictraveller',
            'Summerboy',
            'Barman',
            'Oldexplorer',
            'Blackshirt',
            'Iceprincess',
            'Firemonster',
            'Firemage',
            'Goldknight',
            'Frostgirl',
            'Daemonghast',
            'Spaceexplorer',
            'Greenknight',
            'Darkknight',
            'Battlemonk',
            'Skullmage',
            'Dragon',
            'Endermanhunter',
            'Ghostgirl',
            'Pumpkinboss',
            'Cthulhu',
            'Techarmour',
            'Samurai',
            'Rogue',
            'Creeper',
            'Ninja',
            'Villager',
            'Chicken',
            'Punk Princess',
            'Armored Man',
            'Blue Creeper',
            'Red Slime',
            'Red Knight',
            'Captain United States',
            'Question Block',
            'Blue Jay',
            'Demo Man',
            'Tree Man',
            'Blue Wool',
            'Leaf Man',
            'Red Mage',
            'Girl #2',
            'Blue Skin',
            'Secret Service',
            'Derp Grass Block',
            'Girl #3',
            'Girl #4',
            'Purple Mage',
            'Zombie',
            'Rainbow Cube',
            'Boy #1',
            'Boy #2',
            'Girl #5',
            'Knight',
            'Herobrine',
            'Candidate',
            'Placeholder Candidate',
            'Derp Candidate',
            'Slayer Candidate',
            'Farming Candidate',
            'Cesar Candidate',
            'Mining Candidate',
            'Wizard Candidate',
            'Pets Candidate',
            'Fishing Candidate',
            'Events Candidate',
            'Economist Candidate',
            'Dungeons Candidate',
            'Lonely Philosopher',
            'Baker',
            'Spooky',
            'Oringo',
            'Haymitch',
            'Rick',
            'Elle',
            'End Dealer',
            'Sirius',
            'Bodyguard',
            'Scorpius',
            'Fish Merchant',
            'Catacombs Blacksmith',
            'Ophelia',
            'Gatekeeper',
            'Dungeons Hub Selector',
            'Weirdo 1',
            'Weirdo 2',
            'Weirdo 3',
            'Wizard Quest',
            'Trinity',
            'Tomioka',
            'Winona',
            'Duncan',
            'Charlie',
            'Rainmaker',
            'Master Tactician',
            'Wolf Shaman',
            'Fire Guy',
            'Juliette',
            'Romero Normal',
            'Romero Final',
            'Melancholic Viking',
            'Banker',
            'Event Master',
            'Fisherman',
            'Artist',
            'Farm Merchant',
            'Mine Merchant',
            'Lumber Merchant',
            'Weaponsmith',
            'Armorsmith',
            'Builder',
            'Wool Weaver',
            'Redstone Engineer',
            'Beekeeper',
            'Zog',
            'Pet Collector',
            'Pet Sitter',
            'Hub Selector',
            'Arthur',
            'Salesman Summer',
            'Salesman Halloween',
            'Salesman Christmas',
            'Salesman Easter',
            'Salesman Generic',
            'Carpenter',
            'Dusk',
            'Personal Bank Upgrader',
            'Potato King',
            'Fairy',
            'Wizard',
            'Auction Master',
            'Auction Agent 1',
            'Auction Agent 2',
            'Auction Agent 3',
            'Auction Agent 4',
            'Bazaar',
            'Bazaar Assistant',
            'Community Shop',
            'Shady Cousin',
            'Shady Bartender',
            'Tailor Owner',
            'Tailor Assistant',
            'Slayer',
            'Bartender',
            'Lazy Miner',
            'Gold Forger',
            'Iron Forger',
            'Lapis Miner',
            'Lift Operator',
            'Walter',
            'Desperate Engineer',
            'Guber',
            'Guildford',
            'Gustave',
            'Gulliver',
            'Ice Fisherman',
            'Snowmaker',
            'Frosty',
            'Winter Banker',
            'Einary',
            'St Jerry',
            'Putrid Undead',
            'Revoker Undead',
            'Reaper Undead',
            'Psycho Undead',
            'Ooze Undead',
            'Cannibal Undead',
            'Frank Undead',
            'Flamer Undead',
            'Mute Undead',
            'Leech Undead',
            'Parasite Undead',
            'Tear Undead',
            'Frost Undead',
            'Skull Undead',
            'Walker Undead',
            'Mr Dead Undead',
            'Vader Undead',
            'Bonzo Undead',
            'Giant Undead',
            'Liquid Hot Magma',
            'Entity Liquid Hot Magma',
            'Enderman Liquid Hot Magma',
            'Default Lost Adventurer',
            'Young Lost Adventurer',
            'Unstable Lost Adventurer',
            'Holy Lost Adventurer',
            'Frozen Lost Adventurer',
            'Diamond Guy',
            'Crypt Souleater',
            'Shadow Assassin',
            'King Midas',
            'Minotaur',
            'Minos Inquisitor',
            'Minos Champion',
            'Skeletor Prime',
            'Zombie Commander',
            'Bonzo',
            'Bonzo Summon 1',
            'Bonzo Summon 2',
            'Bonzo Summon 3',
            'Scarf Warrior',
            'Scarf Archer',
            'Scarf Priest',
            'Scarf Mage',
            'Professor',
            'Spirit Bear',
            'Livid',
            'Sadan',
            'Terracotta',
            'Revenant Horror',
            'Enraged Revenant Horror',
            'Blue Shark',
            'Great White Shark',
            'Tiger Shark',
            'Nurse Shark',
            'Jacob',
            'Anita',
            'Melody',
            'Player Jerry',
            'Tony',
            'Goblin',
            'Dwarf Militia 1',
            'Dwarf Militia 2',
            'Dwarf Militia 3',
            'Dwarf Militia 4',
            'Dwarf Militia 5',
            'Dwarf Militia 6',
            'Crystal Sentry',
            'Hephaestus',
            'Forger',
            'Dwarf Citizen Male 1',
            'Dwarf Citizen Male 2',
            'Dwarf Citizen Male 3',
            'Dwarf Citizen Male 4',
            'Dwarf Citizen Female 5',
            'Dwarf Citizen Female 6',
            'Dwarf Citizen Female 7',
            'Goblin Naked 1',
            'Goblin Naked 2',
            'Goblin Naked 3',
            'Goblin Naked 4',
            'Goblin Naked 5',
            'Goblin Armor 1',
            'Goblin Armor 2',
            'Goblin Armor 3',
            'Goblin Armor 4',
            'Goblin Murderlover',
            'Goblin King 1',
            'Dwarf Council Male 1',
            'Dwarf Council Male 2',
            'Dwarf Council Male 3',
            'Dwarf Council Male 4',
            'Dwarf Council Female 5',
            'Dwarf Council Female 6',
            'Dwarf Council Female 7',
            'Dwarf Council Female 8',
            'Dwarf Royalguard Male 1',
            'Dwarf Royalguard Male 2',
            'Dwarf Royalguard Male 3',
            'Dwarf Royalguard Male 4',
            'Dwarf Royalguard Female 5',
            'Dwarf Royalguard Female 6',
            'Dwarf Royalguard Female 7',
            'Dwarf Royalguard Female 8',
            'Emissary Male 1',
            'Emissary Male 2',
            'Emissary Male 3',
            'Emissary Female 1',
            'Emissary Female 2',
            'Emissary Female 3',
            'Emissary Braum',
            'Emissary Sisko',
            'Treasure Horder',
            'Dwarf Banker',
            'Dirt Guy',
            'Puzzler',
            'Old Man Garry',
            'Scoop',
            'Don Expresso',
            'Team Treasurite Boss 1',
            'Team Treasurite Boss 2',
            'Team Treasurite Exec 1',
            'Team Treasurite Exec 2',
            'Team Treasurite Exec 3',
            'Team Treasurite Exec 4',
            'Team Treasurite Grunt 1',
            'Team Treasurite Grunt 2',
            'Team Treasurite Grunt 3',
            'Team Treasurite Grunt 4',
            'Team Treasurite Grunt 5',
            'Team Treasurite Grunt 6',
            'Dwarf Miner Surveyor',
            'Dwarf Miner Female 1',
            'Dwarf Miner Female 2',
            'Dwarf Miner Male 1',
            'Dwarf Miner Male 2',
            'Dwarf Miner Male 3',
            'Bestiary',
            'Grandma Wolf',
            'Archeologist',
            'Shaggy',
            'Jake',
            'Hungry Hiker',
            'Dictator',
            'Beth',
            'Goon',
            'Dante Statue',
            'Treasure Hunter',
            'Friendly Hiker',
            'Mason',
            'Shepherd',
            'Trapper Tony',
            'Tammy',
            'Talbot',
            'Trevor',
            'Farmer Jon',
            'Hunter Ava',
            'Dante Grey',
            'Zombie Miner',
            'Hype Train',
            'Kalhuiki Tribe Man',
            'Kalhuiki Tribe Woman',
            'Kalhuiki Elder',
            'Goblin King',
            'Professor Robot',
            'Kalhuiki Tribe Salesman',
            'Old Prospector',
            'Dwarf Keeper Diamond',
            'Dwarf Keeper Emerald',
            'Dwarf Keeper Gold',
            'Dwarf Keeper Lapis',
            'Jax',
            'Rosetta',
            'Christopher',
            'Amelia',
            'Phantom Spirit',
            'Scary Jerry',
            'Phantom Fisherman',
            'Scarecrow',
            'Decoy',
            'Spirit Decoy',
            'Worker Xavier',
            'Worker Emma',
            'Tyashoi',
            'Museum Curator',
            'Museum Assistant',
            'Bingo',
            'Alixer',
            'Ditto',
            'Ditto Skin',
            'Wiki Librarian',
            'Igor',
            'Kuudra Believer',
            'Arch',
            'Krondor Mage',
            'Mage Male 1',
            'Mage Male 2',
            'Mage Male 3',
            'Mage Male 4',
            'Mage Male 5',
            'Mage Male 6',
            'Mage Male 7',
            'Mage Woman 1',
            'Mage Woman 2',
            'Mage Woman 3',
            'Mage Woman 4',
            'Mage Woman 5',
            'Mage Woman 6',
            'Mage Guard',
            'Mage Banker',
            'Mage Bazaar',
            'Mage Auctioneer',
            'Mage Tavern',
            'Mage Outlaw',
            'Barbarian Duke X 1',
            'Barbarian Duke X 2',
            'Barbarian Duke X 3',
            'Barbarian Duke X 4',
            'Barbarian Duke X 5',
            'Dojo Master',
            'Goliath Barbarian Male 1',
            'Goliath Barbarian Male 2',
            'Goliath Barbarian Male 3',
            'Goliath Barbarian Male 4',
            'Goliath Barbarian Woman 1',
            'Goliath Barbarian Woman 2',
            'Goliath Barbarian Woman 3',
            'Goliath Barbarian Woman 4',
            'Barbarian Minion Shop',
            'Barbarian Emissary',
            'Barbarian Auctionmaster',
            'Barbarian Banker',
            'Barbarian Guard',
            'Barbarian King',
            'Barbarian Captain',
            'Barbarian Merchant',
            'Barbarian Male 1',
            'Barbarian Male 2',
            'Barbarian Male 3',
            'Barbarian Male 4',
            'Barbarian Woman 1',
            'Barbarian Woman 2',
            'Barbarian Woman 3',
            'Barbarian Woman 4',
            'Barbarian Woman 5',
            'Barbarian Woman 6',
            'Barbarian Nerd',
            'Taurus',
            'Odger',
            'Vampire',
            'Kuudra Gatekeeper',
            'Matcho',
            'Mage Dean',
            'Mage Captain Ahone',
            'Mage Royal Guard 1',
            'Mage Royal Guard 2',
            'Mage Queen',
            'Chickzilla',
            'Kuudra Supporter 1',
            'Kuudra Supporter 2',
            'Barbarian Auction Agent 1',
            'Barbarian Auction Agent 2',
            'Barbarian Bazaar',
            'Aura',
            'Maxwell',
            'Ozanne',
            'Jacobus',
            'Security Sloth',
            'Argofay Trafficker',
            'Enigma',
            'Seskel',
            'Chester',
            'Dackinoru',
            'Ashera',
            'Fafnir',
            'Garlacius',
            'Arora',
            'Alabaster',
            'Lazarus',
            'Tybalt',
            'Vreike',
            'Inverted Sirius',
            'Elise',
            'Porhtal',
            'Jacquelle',
            'Deadgehog',
            'Wither Husk',
            'Kay',
            'Reed',
            'Dr Edwin',
            'Dr Phear',
            'Leech Supreme',
            'Motes Grubber',
            'Wizardman',
            'Alatar',
            'Argofay Treemerger',
            'Grandma',
            'Dr Emmett',
            'Rift Kat',
            'Hazmat Dude',
            'Pig',
            'Damia',
            'Shen Agent',
            'Hex',
            'Weird Sailor',
            'Reforge Anvil',
            'Nicole',
            'Spaceman',
            'Sam',
            'Magma Bacteria',
            'Croesus',
            'Fred',
            'Dragon Ritualist',
            'Spider Tamer',
            'Vulcan',
            'Penguin',
            'Hendrik',
            'Frozen Alex',
            'Mysterious Shadow',
            'Xur',
            'Blobbercyst 1',
            'Blobbercyst 2',
            'Blobbercyst 3',
            'Living Metal',
            'Vampire Fledgling',
            'Vampire Boss Male',
            'Rift Boxer 1',
            'Rift Boxer 2',
            'Rift Boxer 3',
            'Primal Fear',
            'Deadline',
            'Darkness Shade',
            'Commitment Phobia',
            'Maths Teacher',
        ],
        NBTCompound,
    ]
    blocks: dict[
        Literal[
            'Acacia Bark',
            'Acacia Log',
            'Acacia Log (rounded)',
            'Acacia Log (rounded, Sideways)',
            'Acacia Log (sideways)',
            'Acacia Log With Snow (rounded, Snow)',
            'Acacia Log With Snow (rounded, Snow, Sideways)',
            'Acacia Planks',
            'Acacia Slabs',
            'Acacia Wood',
            'Adamantite Ore',
            'Aluminum Block',
            'Aluminum Ore',
            'Amber Block',
            'Amber Gem',
            'Amber Ore',
            'Amethyst',
            'Amethyst Block',
            'Amethyst Gem',
            'Amethyst Ore',
            'Ancient Debris',
            'Ancient Debris Block',
            'Ancient Prismarine',
            'Andesite',
            'Andesite Bricks',
            'Aquamarine Block',
            'Aquamarine Gem',
            'Aquatic Wood Log',
            'Ardite Block',
            'Ash Block',
            'Ash Wood',
            'Aspen Log',
            'Aspen Planks',
            'Asphalt',
            'Asphalt Block',
            'Aventurine Gem',
            'Avo Planks',
            'Awakened Draconium',
            'Azalea Leaves',
            'Bamboo Block',
            'Bamboo Mosaic',
            'Bamboo Mosaic Tessera',
            'Bamboo Planks',
            'Barrier',
            'Basalt',
            'Basalt (sideways)',
            'Bedrock',
            'Bedrock Diamond Ore',
            'Birch Bark',
            'Birch Log',
            'Birch Log (rounded)',
            'Birch Log (rounded, Sideways)',
            'Birch Log (sideways)',
            'Birch Log With Snow (rounded, Snow, Sideways)',
            'Birch Log With Snow (rounded, Upright)',
            'Birch Planks',
            'Birch Slabs',
            'Birch Wood',
            'Black Sand',
            'Black Stained Glass',
            'Blackstone',
            'Blackstone Bricks',
            'Blaze Block',
            'Blazewood',
            'Block (blue)',
            'Block (green)',
            'Block (purple)',
            'Block (red)',
            'Block (white)',
            'Block (yellow)',
            'Block Of Bamboo',
            'Block Of Bamboo (sideways)',
            'Block Of Copper',
            'Block Of Netherite',
            'Block Of Raw Iron',
            'Block Of Stripped Bamboo',
            'Block Of Stripped Bamboo (sideways)',
            'Blue Block',
            'Blue Brick',
            'Blue Glowstone',
            'Blue Ice',
            'Blue Sand',
            'Blue Stained Glass',
            'Blue Stonebrick',
            'Blue Team Block',
            'Blurry Crafting Table',
            'Bone Block',
            'Bone Block (sideways)',
            'Boneblock',
            'Bonsai Wood Log',
            'Border Block',
            'Border Wall',
            'Boulder',
            'Brain Coral',
            'Brain Coral (dead)',
            'Brick Bordure',
            'Bricks',
            'Bronze Block',
            'Brown Mushroom Block',
            'Brown Stained Glass',
            'Brownstone',
            'Brownstone Tile',
            'Bubble',
            'Bubble Coral',
            'Bubble Coral (dead)',
            'Budding Amethyst Block',
            'Burning Netherrack',
            'Calcite',
            'Calibrated Sculk Sensor',
            'Carnelian Block',
            'Certes Quartz Block',
            'Charcoal',
            'Cherry Log',
            'Cherry Planks',
            'Cherry Wood Log',
            'Chiseled Deepslate',
            'Chiseled Nether Brick',
            'Chiseled Nether Bricks',
            'Chiseled Polished Blackstone',
            'Chiseled Quartz',
            'Chiseled Red Sandstone',
            'Chiseled Sandstone',
            'Chiseled Stone Bricks',
            'Chiseled Stonebrick',
            'Chlorophyte Brick',
            'Chorus Flower',
            'Citrine Ore',
            'Clay',
            'Clay Block',
            'Claybrick',
            'Claybrick (cracked)',
            'Coal',
            'Coal Block',
            'Coal Ore',
            'Coal Ore Block',
            'Coarse Dirt',
            'Cobalt Block',
            'Cobalt Brick',
            'Cobalt Ore',
            'Cobbled Deepslate',
            'Cobblestone',
            'Cobblestone (brown)',
            'Cobblestone (green)',
            'Cobblestone (purple)',
            'Cobblestone Block',
            'Cobblestone Slabs',
            'Compact Cobblestone',
            'Compressed Ash',
            'Compressed Cobblestone',
            'Compressed Dirt',
            'Compressed Sand',
            'Compressed Snow',
            'Concrete (black)',
            'Concrete (blue)',
            'Concrete (brown)',
            'Concrete (cyan)',
            'Concrete (gray)',
            'Concrete (green)',
            'Concrete (light Blue)',
            'Concrete (light Gray)',
            'Concrete (lilac)',
            'Concrete (lime)',
            'Concrete (magenta)',
            'Concrete (orange)',
            'Concrete (pink)',
            'Concrete (purple)',
            'Concrete (red)',
            'Concrete (white)',
            'Concrete (yellow)',
            'Concrete Powder (black)',
            'Concrete Powder (blue)',
            'Concrete Powder (brown)',
            'Concrete Powder (cyan)',
            'Concrete Powder (gray)',
            'Concrete Powder (green)',
            'Concrete Powder (light Blue)',
            'Concrete Powder (lilac)',
            'Concrete Powder (lime)',
            'Concrete Powder (magenta)',
            'Concrete Powder (orange)',
            'Concrete Powder (pink)',
            'Concrete Powder (purple)',
            'Concrete Powder (red)',
            'Concrete Powder (silver)',
            'Concrete Powder (white)',
            'Concrete Powder (yellow)',
            'Consecrated Soil',
            'Copper Block',
            'Copper Brick',
            'Copper Ore',
            'Copper Ore Block',
            'Cracked Deepslate Bricks',
            'Cracked Deepslate Tiles',
            'Cracked Nether Bricks',
            'Cracked Polished Blackstone Bricks',
            'Cracked Stone',
            'Cracked Stone Brick',
            'Cracked Stone Bricks',
            'Crafting Table',
            'Creeper Ore',
            'Crimsand Block',
            'Crimsandstone Block',
            'Crimson Hyphae',
            'Crimson Nylium',
            'Crimson Planks',
            'Crimson Slabs',
            'Crimson Stem',
            'Crimson Stem (rounded, Sideways)',
            'Crimson Stem (sideways)',
            'Crimson Stem (stripped)',
            'Crimstone Block',
            'Crimtane Brick',
            'Crying Obsidian',
            'Crystal Ball',
            'Crystal Block',
            'Crystal Water Block',
            'Cut Copper',
            'Cut Copper Slabs',
            'Cut Red Sandstone',
            'Cut Sandstone',
            'Cyan Stained Glass',
            'Dark Oak Bark',
            'Dark Oak Log',
            'Dark Oak Log (rounded)',
            'Dark Oak Log (rounded, Sideways)',
            'Dark Oak Log (sideways)',
            'Dark Oak Log With Snow (rounded, Snow)',
            'Dark Oak Log With Snow (rounded, Snow, Sideways)',
            'Dark Oak Planks',
            'Dark Oak Slabs',
            'Dark Oak Wood',
            'Dark Prismarine',
            'Dark Prismarine Bricks',
            'Dead Log',
            'Dead Planks',
            'Deadwood Log',
            'Deepslate',
            'Deepslate (sideways)',
            'Deepslate Block',
            'Deepslate Brick Block',
            'Deepslate Bricks',
            'Deepslate Coal Ore',
            'Deepslate Copper Ore',
            'Deepslate Diamond Ore',
            'Deepslate Emerald Ore',
            'Deepslate Gold Ore',
            'Deepslate Iron Ore',
            'Deepslate Lapis Lazuli Ore',
            'Deepslate Lapis Ore',
            'Deepslate Multi Ore',
            'Deepslate Redstone Ore',
            'Deepslate Tiles',
            'Demonite Brick',
            'Demonite Ore',
            'Dernic Planks',
            'Desert Fossil',
            'Diamond Block',
            'Diamond Block (alpha)',
            'Diamond Gem Lock',
            'Diamond Ore',
            'Diamond Ore Block',
            'Diopside Gem',
            'Diorite',
            'Diorite Bricks',
            'Dirt',
            'Dirt Block',
            'Dirt Cooper Ore',
            'Dirt Diamond Ore',
            'Dirt Emerald Ore',
            'Dirt Lapis Lazuli Ore',
            'Dirt Path',
            'Dirtpath Block',
            'Dirty Cobblestone',
            'Disordered Stone Tiles',
            'Double Smooth Stone Slab',
            'Draconium',
            'Dragonblood Wood Log',
            'Dried Clay',
            'Dried Clay Bricks',
            'Dried Kelp Block',
            'Dripstone Block',
            'Dry Farmland',
            'Ebonsand Block',
            'Ebonsandstone Block',
            'Ebonstone Block',
            'Ebonstone Brick',
            'Elementium Block',
            'Emerald',
            'Emerald Block',
            'Emerald Gem',
            'Emerald Gem Lock',
            'Emerald Ore',
            'Emerald Ore Block',
            'End Crystal',
            'End Gateway',
            'End Stone',
            'End Stone Bricks',
            'Enderite Ore',
            'Enderium Block',
            'Enderium Ore',
            'Endportal (sideways)',
            'Etherium Ore',
            'Eucalyptus Log',
            'Exposed Copper',
            'Exposed Copper Block',
            'Exposed Cut Copper',
            'Farmland',
            'Farmland (moist)',
            'Fir Log',
            'Fir Planks',
            'Fire Coral',
            'Fire Coral (dead)',
            'Floppy Sculk Sensor',
            'Framed Bedrock',
            'Frozen Bone Block',
            'Frozen Slime Block',
            'Funky Portal (black)',
            'Funky Portal (blue)',
            'Funky Portal (brown)',
            'Funky Portal (cyan)',
            'Funky Portal (gray)',
            'Funky Portal (green)',
            'Funky Portal (light Blue)',
            'Funky Portal (light Gray)',
            'Funky Portal (lime)',
            'Funky Portal (magenta)',
            'Funky Portal (orange)',
            'Funky Portal (pink)',
            'Funky Portal (red)',
            'Funky Portal (white)',
            'Funky Portal (yellow)',
            'Garnet Ore',
            'Gilded Blackstone',
            'Glass',
            'Glass (black)',
            'Glass (blue)',
            'Glass (brown)',
            'Glass (cyan)',
            'Glass (gray)',
            'Glass (green)',
            'Glass (light Blue)',
            'Glass (light Gray)',
            'Glass (lilac)',
            'Glass (lime)',
            'Glass (magenta)',
            'Glass (orange)',
            'Glass (pink)',
            'Glass (purple)',
            'Glass (red)',
            'Glass (white)',
            'Glass (yellow)',
            'Glass Block',
            'Glazed Terracotta (black)',
            'Glazed Terracotta (blue)',
            'Glazed Terracotta (brown)',
            'Glazed Terracotta (cyan)',
            'Glazed Terracotta (gray)',
            'Glazed Terracotta (green)',
            'Glazed Terracotta (light Blue)',
            'Glazed Terracotta (light Gray)',
            'Glazed Terracotta (lilac)',
            'Glazed Terracotta (lime)',
            'Glazed Terracotta (magenta)',
            'Glazed Terracotta (magenta, Sideways)',
            'Glazed Terracotta (orange)',
            'Glazed Terracotta (pink)',
            'Glazed Terracotta (purple)',
            'Glazed Terracotta (red)',
            'Glazed Terracotta (white)',
            'Glazed Terracotta (yellow)',
            'Glitch Wood',
            'Glitched Bedrock',
            'Glow Lichen On Dirt',
            'Glow Lichen On Moss',
            'Glow Lichen On Rooted Dirt',
            'Glow Lichen On Stone',
            'Glowing Iron Block',
            'Glowing Obsidian',
            'Glowstone',
            'Gold',
            'Gold Block',
            'Gold Block (alpha)',
            'Gold Brick',
            'Gold Bricks',
            'Gold Ore',
            'Gold Ore Block',
            'Gold Tile',
            'Goldblock',
            'Grain Of Sand',
            'Granite',
            'Granite Block',
            'Granite Bricks',
            'Grass (alpha)',
            'Grass Block',
            'Grass Block (dark Oak)',
            'Grass Block (forest)',
            'Grass Block (taiga)',
            'Grass Block (alpha)',
            'Grass Path',
            'Gravel',
            'Gravel (alpha)',
            'Gray Brick',
            'Gray Stained Glass',
            'Gray Stucco',
            'Green Block',
            'Green Brick',
            'Green Gem',
            'Green Stained Glass',
            'Green Stucco',
            'Green Team Block',
            'Grimwood Log',
            'Grimwood Planks',
            'Grout',
            'Hardened Crimsand Block',
            'Hardened Ebonsand Block',
            'Hardened Pearlsand Block',
            'Hardened Sand Block',
            'Heat Block',
            'Hellbark Log',
            'Hellbark Planks',
            'Hellstone',
            'Hellstone Brick',
            'Hepatizon Block',
            'Honey Block',
            'Horn Coral',
            'Horn Coral (dead)',
            'Hydrated Farmland',
            'Ice',
            'Ice Block',
            'Ice Brick',
            'Inner Beacon',
            'Inner Mushroom Block',
            'Iridescent Brick',
            'Iron',
            'Iron Block',
            'Iron Block (alpha)',
            'Iron Block (beta)',
            'Iron Block Ore',
            'Iron Ore',
            'Iron Ore Block',
            'Ironblock',
            'Jacaranda Log',
            'Jacaranda Planks',
            'Jakarta Log',
            'Jungle Bark',
            'Jungle Log',
            'Jungle Log (rounded)',
            'Jungle Log (rounded, Sideways)',
            'Jungle Log (sideways)',
            'Jungle Log With Snow (rounded, Snow)',
            'Jungle Log With Snow (rounded, Snow, Sideways)',
            'Jungle Planks',
            'Jungle Slabs',
            'Jungle Wood',
            'Knightslime Block',
            'Kousa Log',
            'Kousa Planks',
            'Lapis',
            'Lapis Block',
            'Lapis Lazuli Block',
            'Lapis Lazuli Ore',
            'Lapis Ore',
            'Lathanite Ore',
            'Lava',
            'Lava Ore',
            'Lavawood',
            'Lead Ore',
            'Light Blue Stained Glass',
            'Light Gray Stained Glass',
            'Light Planks',
            'Light Stone',
            'Lightning Rod Tip',
            'Lihzahrd Brick',
            'Lime Stained Glass',
            'Living Mahogany',
            'Living Rock',
            'Living Wood',
            'Lodestone',
            'Log',
            'Log With Carved Creeper',
            'Log With Leaves',
            'Luminite Brick',
            'Luminite Ore',
            'Magenta Stained Glass',
            'Magic Log',
            'Magic Planks',
            'Magma',
            'Magma Block',
            'Magma Bricks',
            'Magnesium Ore',
            'Mahogany Leaf Block',
            'Mahogany Log',
            'Mahogany Planks',
            'Malachite Block',
            'Malachite Ore',
            'Manasteel Block',
            'Mangrove Log',
            'Mangrove Log (rounded)',
            'Mangrove Log (rounded, Sideways)',
            'Mangrove Log (sideways)',
            'Mangrove Planks',
            'Mangrove Root',
            'Mangrove Wood',
            'Manyullyn Block',
            'Marble Block',
            'Mario Bricks',
            'Mario Floor Block',
            'Maroon Block',
            'Mega Compressed Ash',
            'Metalic Base (flat)',
            'Metalic Base (glossy)',
            'Metalic Base (high Gloss)',
            'Metallic Voidstone',
            'Meteor Shard',
            'Meteorite Brick',
            'Mithril Ore',
            'Molten Block',
            'Morado Log',
            'Morado Planks',
            'Moss Block',
            'Mossy Boulder',
            'Mossy Cobblestone',
            'Mossy Cobblestone (flat)',
            'Mossy Cobblestone Slabs',
            'Mossy Stone',
            'Mossy Stone (stage 0)',
            'Mossy Stone (stage 1)',
            'Mossy Stone (stage 10)',
            'Mossy Stone (stage 11)',
            'Mossy Stone (stage 12)',
            'Mossy Stone (stage 13)',
            'Mossy Stone (stage 14)',
            'Mossy Stone (stage 15)',
            'Mossy Stone (stage 16)',
            'Mossy Stone (stage 17)',
            'Mossy Stone (stage 18)',
            'Mossy Stone (stage 19)',
            'Mossy Stone (stage 2)',
            'Mossy Stone (stage 20)',
            'Mossy Stone (stage 21)',
            'Mossy Stone (stage 3)',
            'Mossy Stone (stage 4)',
            'Mossy Stone (stage 5)',
            'Mossy Stone (stage 6)',
            'Mossy Stone (stage 7)',
            'Mossy Stone (stage 8)',
            'Mossy Stone (stage 9)',
            'Mossy Stone Brick',
            'Mossy Stone Brick Slabs',
            'Mossy Stone Bricks',
            'Mossy Wood',
            'Mud',
            'Mud Block',
            'Mud Bricks',
            'Muddy Mangrove Roots',
            'Muddy Mangrove Roots (sideways)',
            'Mudstone Brick',
            'Multi Ore',
            'Multi Planks',
            'Multiore',
            'Mushroom Block',
            'Mushroom Stem',
            'Mushroom Stem (sideways)',
            'Mycelium',
            'Mythril Brick',
            'Mythril Ore',
            'Nether Bricks',
            'Nether Gold',
            'Nether Gold Ore',
            'Nether Gold Ore Block',
            'Nether Grout',
            'Nether Portal',
            'Nether Quartz Ore',
            'Nether Quartz Ore Block',
            'Nether Wart Block',
            'Netherite',
            'Netherite Block',
            'Netherquarz',
            'Netherrack',
            'Netherrack Block',
            'Nickel Ore',
            'Oak Bark',
            'Oak Log',
            'Oak Log (rounded)',
            'Oak Log (rounded, Sideways)',
            'Oak Log (sideways)',
            'Oak Log With Snow (rounded, Snow)',
            'Oak Log With Snow (rounded, Snow, Sideways)',
            'Oak Planks',
            'Oak Slabs',
            'Oak Wood',
            'Obsidian',
            'Obsidian Brick',
            'Ochre Froglight',
            'Onyx Gem',
            'Orange Sand',
            'Orange Stained Glass',
            'Ore (light Blue)',
            'Ore (purple)',
            'Ore (red)',
            'Ore (yellow)',
            'Ore Of Shadow',
            'Ornate Diamond Block',
            'Ornate Dirt Block',
            'Ornate Gold Block',
            'Ornate Iron Block',
            'Ornate Lapis Lazuli Block',
            'Ornate Netherite',
            'Ornate Redstone Block',
            'Ornate Stone',
            'Ornate Wood Block',
            'Oxidized Copper Block',
            'Oxidized Cut Copper',
            'Packed Ice',
            'Packed Ice Block',
            'Packed Mud',
            'Palm Bark',
            'Palm Log',
            'Palm Log (rounded, Sideways)',
            'Palm Planks',
            'Path Block',
            'Pearlescent Froglight',
            'Pearlsand Block',
            'Pearlsandstone Block',
            'Pearlstone Block',
            'Pearlstone Brick',
            'Peridot Block',
            'Pig Iron Block',
            'Pine Log',
            'Pine Planks',
            'Pink Brick',
            'Pink Ice Block',
            'Pink Ore',
            'Pink Stained Glass',
            'Pink Team Block',
            'Piston',
            'Piston (sideways)',
            'Platinum Brick',
            'Platinum Ore',
            'Plutonium Ore',
            'Podzol',
            'Podzol Block',
            'Polished Andesite',
            'Polished Basalt',
            'Polished Basalt (sideways)',
            'Polished Blackstone',
            'Polished Blackstone Bricks',
            'Polished Dark Prismarine',
            'Polished Deepslate',
            'Polished Diorite',
            'Polished Endstone',
            'Polished Granite',
            'Polished Marble',
            'Polished Prismarine',
            'Polished Stone',
            'Powder Snow',
            'Prismarine',
            'Prismarine Brick',
            'Prismarine Bricks',
            'Purple Block',
            'Purple Gem',
            'Purple Ice Block',
            'Purple Log',
            'Purple Stained Glass',
            'Purpur Block',
            'Purpur Pillar',
            'Purpur Pillar (sideways)',
            'Purpur Tile',
            'Quartz Block',
            'Quartz Bricks',
            'Quartz Column',
            'Quartz Gem',
            'Quartz Pillar',
            'Quartz Pillar (sideways)',
            'Queens Slime Block',
            'Rainbow Gem',
            'Rainbow Nether Quartz Ore',
            'Raw Copper Block',
            'Raw Gold Block',
            'Raw Iron',
            'Raw Iron Block',
            'Red Block',
            'Red Brick',
            'Red Ice Block',
            'Red Magma',
            'Red Mushroom Block',
            'Red Nether Brick',
            'Red Nether Bricks',
            'Red Sand',
            'Red Sandstone',
            'Red Stained Glass',
            'Red Stucco',
            'Red Team Block',
            'Red Wood',
            'Red Wood With Snow (rounded, Snow)',
            'Redstone',
            'Redstone (blue)',
            'Redstone (green)',
            'Redstone (orange)',
            'Redstone (purple)',
            'Redstone (yellow)',
            'Redstone Block',
            'Redstone Ore',
            'Redstone Ore (off)',
            'Redwood',
            'Redwood Log',
            'Redwood Log (sideways)',
            'Redwood Planks',
            'Reinforced Deepslate',
            'Rock',
            'Rooted Dirt',
            'Rooted Sand',
            'Rose Gold Block',
            'Rose Quartz',
            'Rose Quartz Block',
            'Rose Quartz Gem',
            'Rosewood Log',
            'Rosewood Planks',
            'Ruby',
            'Ruby Block',
            'Ruby Gem',
            'Ruby Ore',
            'Ruby Ore On Granite',
            'Sand',
            'Sand Block',
            'Sandfall Block',
            'Sandstone',
            'Sandstone Block',
            'Sandstone Brick',
            'Saphire Ore',
            'Sapphire Block',
            'Sapphire Gem',
            'Sapphire Ore',
            'Sculk Block',
            'Sculk Catalyst',
            'Sculk Chute',
            'Sculk Sensor (activated)',
            'Sculk Sensor (inactive)',
            'Sculk Shrieker',
            'Sculk Tracker',
            'Sculk Trap',
            'Sculk Vein',
            'Scute Block',
            'Sea Lantern',
            'Searing Stone',
            'Shroomite Plating',
            'Shroomlight',
            'Shulker Bullet',
            'Silky Jewel Block',
            'Silt Block',
            'Silver Birch Log',
            'Silver Block',
            'Silver Brick',
            'Silver Ore',
            'Sky Planks',
            'Slate',
            'Slate (chiseled)',
            'Slate (polished)',
            'Slime',
            'Slime Ball',
            'Slime Block',
            'Slimeblock',
            'Slimesteel Block',
            'Slush Block',
            'Smooth Basalt',
            'Smooth Granite Block',
            'Smooth Marble Block',
            'Smooth Quartz',
            'Smooth Red Sandstone',
            'Smooth Sandstone',
            'Smooth Stone Block',
            'Snow Block',
            'Snow Brick',
            'Snowball',
            'Snowfall Block',
            'Snowy Granite',
            'Snowy Grass',
            'Snowy Grass Block',
            'Soul Sand',
            'Soul Soil',
            'Spirit Jewel',
            'Sponge',
            'Spongebob (body)',
            'Spruce Bark',
            'Spruce Bush',
            'Spruce Log',
            'Spruce Log (rounded)',
            'Spruce Log (sideways)',
            'Spruce Log With Snow (rounded, Snow)',
            'Spruce Log With Snow (rounded, Snow, Sideways)',
            'Spruce Planks',
            'Spruce Slabs',
            'Spruce Wood',
            'Sticky Piston',
            'Sticky Piston (sideways)',
            'Still Lava',
            'Stipped Oak Log',
            'Stipped Oak Log (sideways)',
            'Stone',
            'Stone Ball',
            'Stone Block',
            'Stone Brick',
            'Stone Brick Block',
            'Stone Brick Slabs',
            'Stone Bricks',
            'Stone Bricks (cracked)',
            'Stone Bricks (mossy)',
            'Stone Pillar',
            'Stone Slabs',
            'Stone Tiles',
            'Stonebricks',
            'Stripped Acacia Bark',
            'Stripped Acacia Log',
            'Stripped Acacia Log (sideways)',
            'Stripped Acacia Wood',
            'Stripped Bamboo Block',
            'Stripped Birch Bark',
            'Stripped Birch Log',
            'Stripped Birch Log (sideways)',
            'Stripped Birch Wood',
            'Stripped Crimson Hyphae',
            'Stripped Crimson Stem (sideways)',
            'Stripped Dark Oak Bark',
            'Stripped Dark Oak Log',
            'Stripped Dark Oak Log (sideways)',
            'Stripped Dark Oak Wood',
            'Stripped Jungle Bark',
            'Stripped Jungle Log',
            'Stripped Jungle Log (sideways)',
            'Stripped Jungle Wood',
            'Stripped Mangrove Log',
            'Stripped Mangrove Log (sideways)',
            'Stripped Mangrove Wood',
            'Stripped Oak Bark',
            'Stripped Oak Log',
            'Stripped Oak Log (sideways)',
            'Stripped Oak Wood',
            'Stripped Spruce Bark',
            'Stripped Spruce Log',
            'Stripped Spruce Log (sideways)',
            'Stripped Spruce Wood',
            'Stripped Warped Stem',
            'Stripped Warped Stem (sideways)',
            'Structure Void',
            'Sulphur Ore',
            'Sunplate Block',
            'Super Compressed Ash',
            'Talking Block Of Coal',
            'Target Block',
            'Terracotta',
            'Terracotta (black)',
            'Terracotta (blue)',
            'Terracotta (brown)',
            'Terracotta (cyan)',
            'Terracotta (gray)',
            'Terracotta (green)',
            'Terracotta (light Blue)',
            'Terracotta (light Gray)',
            'Terracotta (lime)',
            'Terracotta (magenta)',
            'Terracotta (pink)',
            'Terracotta (purple)',
            'Terracotta (red)',
            'Terracotta (yellow)',
            'Terracotta (lilac)',
            'Terracotta (orange)',
            'Terracotta (white)',
            'Terraria Ruby Gem Lock',
            'Thin Ice',
            'Tin Brick',
            'Tin Ore',
            'Tinkers Bronze Block',
            'Tinted Glass Block',
            'Titanium Ore',
            'Topaz Gem',
            'Topaz Ore',
            'Tube Coral',
            'Tube Coral (dead)',
            'Tuff',
            'Tungsten Brick',
            'Umbran Log',
            'Umbran Planks',
            'Uranium Ore',
            'Verdant Froglight',
            'Voidstone',
            'Voidstone Ore',
            'Voidstone Tile',
            'Walnut Wood',
            'Warped Hyphae',
            'Warped Nylium',
            'Warped Planks',
            'Warped Slabs',
            'Warped Stem',
            'Warped Stem (rounded)',
            'Warped Stem (rounded, Sideways)',
            'Warped Stem (sideways)',
            'Warped Wart Block',
            'Watchful Aspen Log',
            'Water',
            'Waterlogged Mangrove Roots',
            'Wax Block',
            'Weathered Brownstone',
            'Weathered Brownstone Tile',
            'Weathered Copper Block',
            'Weathered Cut Copper',
            'Wet Sponge',
            'White Glowstone',
            'White Mushroom Block',
            'White Sand',
            'White Stained Glass',
            'White Team Block',
            'Willow Log',
            'Willow Planks',
            'Wood Cube (acacia)',
            'Wood Cube (birch)',
            'Wood Cube (dark Oak)',
            'Wood Cube (jungle)',
            'Wood Cube (oak)',
            'Wood Cube (spruce)',
            'Wood Log',
            'Wool (black)',
            'Wool (blue)',
            'Wool (brown)',
            'Wool (cyan)',
            'Wool (dark Red)',
            'Wool (gray)',
            'Wool (green)',
            'Wool (light Blue)',
            'Wool (light Gray)',
            'Wool (lilac)',
            'Wool (lime)',
            'Wool (magenta)',
            'Wool (orange)',
            'Wool (pink)',
            'Wool (purple)',
            'Wool (rainbow)',
            'Wool (red)',
            'Wool (white)',
            'Wool (yellow)',
            'Yellow Snow',
            'Yellow Stained Glass',
            'Yellow Stucco',
            'Yellow Team Block',
            'Yucca Log',
            'Yucca Planks',
            'Zircon Gem',
            'Mangrove Roots',
        ],
        NBTCompound,
    ]
    animals: dict[
        Literal[
            'Sloth',
            'Goat',
            'Otter',
            'Crazy Fox',
            'Blue Axolotl',
            'Glow Squid',
            'Fly',
            'Cat',
            'Clownfish',
            'Blue Tropical Fish',
            'Red Snapper Tropical Fish',
            'Cotton Candy Tropical Fish',
            'Brown Bunny',
            'Monkey',
            'Doge',
            'Spitter Ant',
            'Gatherer Ant',
            'Flying Ant ',
            'Water Skier Ant',
            'Brute Ant',
            'Ocelot',
            'Rat',
            'Sheep',
            'Dinosaur',
            'Frog',
            'Capybara',
            'Pufferfish',
            'Royal Pufferfish',
            'Wolf Pilot',
            'Fox Pilot',
            'Tiger',
            'Brown Dog',
            'Mole',
            'Raccoon',
            'Pug',
            'Beagle',
            'Shark',
            'Penguin',
            'Beaver',
        ],
        NBTCompound,
    ]
    colors: dict[
        Literal[
            'Maroon',
            'Crimson',
            'Red',
            'Salmon',
            'Orange',
            'Goldenrod',
            'Yellow',
            'Olive',
            'Dark Green',
            'Sea Green',
            'Medium Sea Green',
            'Lime Green',
            'Lime',
            'Light Cyan',
            'Baby Blue',
            'Dodger Blue',
            'Azure Blue',
            'Cyan',
            'Blue',
            'Dark Cyan',
            'Midnight Blue',
            'Indigo',
            'Deep Pink',
            'Magenta',
            'Hot Pink',
            'Coral',
            'Cream',
            'Mokka',
            'Brown',
            'White',
            'Light Grey',
            'Grey',
            'Black',
        ],
        NBTCompound,
    ]
    diamond_font: dict[
        Literal[
            'Number 0',
            'Number 1',
            'Number 2',
            'Number 3',
            'Number 4',
            'Number 5',
            'Number 6',
            'Number 7',
            'Number 8',
            'Number 9',
            'Letter A',
            'Letter B',
            'Letter C',
            'Letter D',
            'Letter E',
            'Letter F',
            'Letter G',
            'Letter H',
            'Letter I',
            'Letter J',
            'Letter K',
            'Letter L',
            'Letter M',
            'Letter N',
            'Letter O',
            'Letter P',
            'Letter Q',
            'Letter R',
            'Letter S',
            'Letter T',
            'Letter U',
            'Letter V',
            'Letter W',
            'Letter X',
            'Letter Y',
            'Letter Z',
        ],
        NBTCompound,
    ]
    garden: dict[
        Literal[
            'Garden Gnome',
            'Bird House',
            'Shell',
            'Potted Succulents 1',
            'Potted Succulents 2',
            'Potted Plant with Flowers',
            'Flowers in a Boot',
            'Log',
            'Light Blue Flower',
            'Sunflower',
            'Bush with Pink Flowers',
            'Bush with Yellow Flowers',
            'Cherry Blossoms',
            'Rose',
            'Ladybug',
            'Snail',
            'Cactus in Basket',
            'Flowerpot',
            'Lavender Plant',
            'Cactus Plant',
            'Eggplant',
            'Eggplant Bag',
            "Plantera's Bulb",
            'Plant Snail',
            'Piranha Plant',
            'Chorus Plant',
            'Potted Dahlie Plant',
            'Potted Azalea Plant',
            'Potted Camellia Plant',
            'Potted Salvia Plant',
            'Potted Rose Plant',
            'Potted Dahlia Plant',
            'Potted Lavender Plant',
            'Potted Orchid Plant',
            'Potted Lilac Plant',
            'Potted Marigold Plant',
        ],
        NBTCompound,
    ]
    kitchen: dict[
        Literal[
            'Toaster',
            'Fruit Basket #1',
            'Can of Soup',
            'Honey',
            'Bag of Herbs',
            'Microwave',
            'Pepper Cellar',
            'Salt Cellar',
            'Dishes',
            'Soap Dispenser',
            'Pepper Cellar #2',
            'Salt Cellar #2',
            'Fruit Basket #2',
            'Soup',
            'Stove',
            'Coffee Machine',
            'Cup (Purple)',
            'Cup (Blue)',
            'Cup (Green)',
            'Cup (Yellow)',
            'Cup (Orange)',
            'Cup (Red)',
            'Bread on a Plate',
            'Sliced Bread on a Plate',
            'Bread Toaster',
            'Recipe Book',
            'Bag of Sugar',
            'Blender',
            'Bag of Flour',
            'Waffle Iron',
        ],
        NBTCompound,
    ]
    lucky_blocks: dict[
        Literal[
            'Lucky Block',
            'Lucky Block (cyan)',
            'Lucky Block (black)',
            'Lucky Block (blue)',
            'Lucky Block (brown)',
            'Lucky Block (dark Blue)',
            'Lucky Block (dark Gray)',
            'Lucky Block (dark Red)',
            'Lucky Block (gray)',
            'Lucky Block (green)',
            'Lucky Block (light Blue)',
            'Lucky Block (light Gray)',
            'Lucky Block (light Purple)',
            'Lucky Block (lime)',
            'Lucky Block (magenta)',
            'Lucky Block (orange)',
            'Lucky Block (pink)',
            'Lucky Block (purple)',
            'Lucky Block (red)',
            'Lucky Block (tinted)',
            'Lucky Block (turquoise)',
            'Lucky Block (white)',
            'Lucky Block (yellow)',
        ],
        NBTCompound,
    ]
    minion_skins: dict[
        Literal[
            'Basketball',
            'Melon',
            'Killer',
            'Skull',
            'Lady Bug',
            'Pumpkin',
            'Present',
            'Penguin',
            'Sloth',
            'Bunny',
            'Ghost',
            'Ice Lolly',
            'Gingerbread Man',
            'Sun',
            'Tropical Bird 2',
            'Ender',
            'Pink Bunny',
            'White Tiger',
            'Reindeer',
            'Grinch',
            'Bee',
            'Pufferfish',
            'Undead',
            'Easter Egg',
            'Scarecrow',
            'Fish',
            'Festive Zombie',
            'Sandcastle',
            'Clownfish',
            'Tropical Bird 1',
            'Beach Ball',
            'Happy Emoji',
            'Festive Jerry',
            'Mummy',
            'Hermit Crab',
            'Shark',
            'Festive Skeleton',
            'Pink Frosted Donut',
            'Cyclops',
            'Ice Cream',
        ],
        NBTCompound,
    ]
    monitor_font: dict[
        Literal[
            'Number 0',
            'Number 1',
            'Number 2',
            'Number 3',
            'Number 4',
            'Number 5',
            'Number 6',
            'Number 7',
            'Number 8',
            'Number 9',
            'Letter A',
            'Letter B',
            'Letter C',
            'Letter D',
            'Letter E',
            'Letter F',
            'Letter G',
            'Letter H',
            'Letter I',
            'Letter J',
            'Letter K',
            'Letter L',
            'Letter M',
            'Letter N',
            'Letter O',
            'Letter P',
            'Letter Q',
            'Letter R',
            'Letter S',
            'Letter T',
            'Letter U',
            'Letter V',
            'Letter W',
            'Letter X',
            'Letter Y',
            'Letter Z',
        ],
        NBTCompound,
    ]
    rainbow_font: dict[
        Literal[
            'Number 0',
            'Number 1',
            'Number 2',
            'Number 3',
            'Number 4',
            'Number 5',
            'Number 6',
            'Number 7',
            'Number 8',
            'Number 9',
            'Letter A',
            'Letter B',
            'Letter C',
            'Letter D',
            'Letter E',
            'Letter F',
            'Letter G',
            'Letter H',
            'Letter I',
            'Letter J',
            'Letter K',
            'Letter L',
            'Letter M',
            'Letter N',
            'Letter O',
            'Letter P',
            'Letter Q',
            'Letter R',
            'Letter S',
            'Letter T',
            'Letter U',
            'Letter V',
            'Letter W',
            'Letter X',
            'Letter Y',
            'Letter Z',
        ],
        NBTCompound,
    ]
    redstone_font: dict[
        Literal[
            'Number 0',
            'Number 1',
            'Number 2',
            'Number 3',
            'Number 4',
            'Number 5',
            'Number 6',
            'Number 7',
            'Number 8',
            'Number 9',
            'Letter A',
            'Letter B',
            'Letter C',
            'Letter D',
            'Letter E',
            'Letter F',
            'Letter G',
            'Letter H',
            'Letter I',
            'Letter J',
            'Letter K',
            'Letter L',
            'Letter M',
            'Letter N',
            'Letter O',
            'Letter P',
            'Letter Q',
            'Letter R',
            'Letter S',
            'Letter T',
            'Letter U',
            'Letter V',
            'Letter W',
            'Letter X',
            'Letter Y',
            'Letter Z',
        ],
        NBTCompound,
    ]
    pet_skins: dict[
        Literal[
            'Neon Yellow Sheep',
            'Blue Elephant',
            'White Sheep',
            'Dark Wither Skeleton',
            'Grown-up Baby Yeti',
            'Rose Rabbit',
            'Neon Blue Ender Dragon',
            'Snow Tiger Ocelot',
            'Pink Sheep',
            'Light Blue Sheep',
            'Red Snubfin Dolphin',
            'Baby Megalodon',
            'Baby Chick Chicken',
            'Green Elf Jerry',
            'Pastel Ender Dragon',
            'Handsome Jerry',
            'Neon Green Sheep',
            'Thinking Rock',
            'Smiling Rock',
            'Neon Red Ender Dragon',
            'Green Elephant',
            'Purple Sheep',
            'Purple Snubfin Dolphin',
            'Green Snubfin Dolphin',
            'Zombie Skeleton Horse',
            'Dark Wolf',
            'Undead Ender Dragon',
            'Pretty Rabbit',
            'Spooky Enderman',
            'Aquamarine Rabbit',
            'Neon Red Sheep',
            'Fortified Silverfish',
            'Red Elf Jerry',
            'Onyx Black Cat',
            'Golden Monkey',
            'Neon Purple Ender Dragon',
            'Light Green Sheep',
            'Cool Rock',
            'Watcher Guardian',
            'Ivory Black Cat',
            'Laughing Rock',
            'Purple Elephant',
            'Pink Elephant',
            'Red Elephant',
            'Saber-Tooth Tiger',
            'Gold Macaw Parrot',
            'Derpy Rock',
            'Ice Phoenix',
            'Beagle Hound',
            'Black Sheep',
            'Embarrassed Rock',
            'Orange Elephant',
            'Orca Blue Whale',
            'Fossilized Silverfish',
            'Neon Blue Sheep',
        ],
        NBTCompound,
    ]
    food: dict[
        Literal[
            'Strawberry Jam',
            'Sushi Mackerel',
            'Sushi Salmon',
            'Ham #1',
            'Orange #1',
            'Lettuce',
            'Green Apple',
            'Red Apple',
            'Purple Grapes',
            'Cheese',
            'Melon #1',
            'Melon #2',
            'Open Melon',
            'Cut Open Melon',
            'Bento Box',
            'Sushi Roll #1',
            'Hamburger #1',
            'Hamburger #2',
            'Hamburger #3',
            'Fries #1',
            'Bowl of Noodles #1',
            'White Frosted Donut',
            'Pink Frosted Donut',
            'Chocolate Frosted Donut',
            'Coconut',
            'Cup of Tea',
            'Bread',
            'Glass of Amber Brew',
            'Medieval Brew',
            'Tomato',
            'Muffin #1',
            'Bacon Sandwich',
            'Picnic Basket',
            'Cherry Pie on Stand',
            'Blueberry Pie on Stand',
            'Spaghetti and Meatballs',
            'Soup #1',
            'Pancakes with Syrup',
            'Sushi Roll on Plate',
            'Bowl of Miso Soup',
            'Sushi Shrimp',
            'Sushi Egg',
            'Japanese Green Tea',
            'Small Cake',
            'Pumpkin',
            'Cup of Milk',
            'Glass of Cola',
            'Cut Lemon',
            'Cherry',
            'Cookie',
            'Taco #1',
            'OrieOh Sandwich',
            'OrieOh Biscuit',
            'Baked Potato',
            'Waffle',
            'Popcorn #1',
            'Beans',
            'Deep Dish Pizza',
            'Cooked Lobster',
            'Lemonade #1',
            'Roasted Pig',
            'Gingerbread House',
            'Bacon #1',
            'Sundae',
            'Arizona',
            'Raisin Box',
            'Orange #2',
            'Melon #3',
            'Melon Slice',
            'Sushi Roll #2',
            'Hamburger #4',
            'Fries #2',
            'Bowl of Noodles #2',
            'Coffee Mug',
            'Hot Coco Mug',
            'Hot Dog',
            'Ground Beef',
            'Salsa',
            'Empty Tin Cup',
            'Oatmeal',
            'Apple Salad',
            'Pepper Salad',
            'Radish Salad',
            'Kiwi Mango Bowl',
            'Tropical Fruit Bowl',
            'Cake',
            'Green Grapes',
            'Chives',
            'Ham #2',
            'Muffin #2',
            'Jar of Pickles',
            'Key Lime Pie',
            'Blueberry Pie',
            'Taco #2',
            'Coconut Drink',
            'Soup #2',
            'Popcorn #2',
            'Pizza',
            'Lemonade #2',
            'Raw Beef',
            'Pancakes',
            'Bacon #2',
        ],
        NBTCompound,
    ]
    bathroom: dict[
        Literal[
            'Soap on a Plate',
            'Rubber Ducky',
            'Tissue Box',
            'Bottle',
            'Yellow Candle',
            'First Aid Kit #1',
            'First Aid Kit #2',
            'Toilet Paper',
            'Shampoo Bottle',
            'Toilet Paper Dispenser',
            'Spa Candle',
            'Sponge',
            'Towels',
        ],
        NBTCompound,
    ]
    bedroom: dict[
        Literal[
            'Lit Candle',
            'Folded Shirts',
            'Folded Pants',
            'Teddy Bear #1',
            'Basket',
            'Nightstand with Remote Control',
            'Nightstand',
            'Teddy Bear #2',
        ],
        NBTCompound,
    ]
    economy: dict[
        Literal[
            'Money Stack',
            'Lucky Cat #1',
            'Card Reader #1',
            'Grocery Bag',
            'Jungle Crate',
            'Bell',
            'Box',
            'Crate',
            'Lucky Cat #2',
            'Card Reader #2',
            'Money Bag',
            'Coin',
            'Piggy Bank',
            'Cash Register',
            'Stack of Cash',
        ],
        NBTCompound,
    ]
    music: dict[
        Literal[
            'Speaker #1',
            'Speaker #2',
            'CD Case',
            'Record Player #1',
            'Studio Mic',
            'Stack of CDs',
            'Record Player #2',
            'Microphone',
            'Speaker #3',
            'Drum',
            'Jukebox',
            'Radio',
            'Banjo',
            'Piano Keys',
        ],
        NBTCompound,
    ]


SKULL_DATA_FILE = HERE / 'skulls.json'


def read_skull_data() -> SkullData:
    raw = json.loads(SKULL_DATA_FILE.read_text(encoding='utf-8'))
    return {
        key.lower().replace(' ', '_'): {
            sub_key: NBTCompound()
            .put('Id', NBTString(sub_value['id']))
            .put('hypixelPopulated', NBTInt(1))
            .put(
                'Properties',
                NBTCompound().put(
                    'textures',
                    NBTList(
                        [
                            NBTCompound()
                            .put('Signature', NBTString('I love https://github.com/69Jesse'))
                            .put('Value', NBTString(sub_value['texture']))
                        ]
                    ),
                ),
            )
            for sub_key, sub_value in value.items()
        }
        for key, value in raw.items()
    }  # type: ignore


SKULL_DATA: SkullData = read_skull_data()
