from typing import Literal


__all__ = (
    'POTION_EFFECTS',
    'DAMAGE_CAUSES',
    'ALL_POSSIBLE_ENCHANTMENTS',
    'ENCHANTMENT_TO_ID',
    'INVENTORY_SLOTS',
    'NON_SPECIAL_ITEM_KEYS',
    'DAMAGEABLE_ITEM_KEYS',
    'LEATHER_ARMOR_KEYS',
    'ALL_POSSIBLE_ITEM_KEYS',
    'LOCATIONS',
)


POTION_EFFECTS = Literal[
    'speed',
    'slowness',
    'haste',
    'mining_fatigue',
    'strength',
    'instant_health',
    'instant_damage',
    'jump_boost',
    'nausea',
    'regeneration',
    'resistance',
    'fire_resistance',
    'water_breathing',
    'invisibility',
    'blindness',
    'night_vision',
    'hunger',
    'weakness',
    'poison',
    'wither',
    'health_boost',
    'absorption',
]


DAMAGE_CAUSES = Literal[
    'entity_attack',
    'projectile',
    'suffocation',
    'fall',
    'lava',
    'fire',
    'fire_tick',
    'drowning',
    'starvation',
    'poison',
    'thorns',
]


ALL_POSSIBLE_ENCHANTMENTS = Literal[
    'protection',
    'fire_protection',
    'feather_falling',
    'blast_protection',
    'projectile_protection',
    'respiration',
    'aqua_affinity',
    'thorns',
    'depth_strider',
    'sharpness',
    'smite',
    'bane_of_arthropods',
    'knockback',
    'fire_aspect',
    'looting',
    'efficiency',
    'silk_touch',
    'unbreaking',
    'fortune',
    'power',
    'punch',
    'flame',
    'infinity',
    'luck_of_the_sea',
    'lure',
]


ENCHANTMENT_TO_ID: dict[ALL_POSSIBLE_ENCHANTMENTS, int] = {
    'protection': 0,
    'fire_protection': 1,
    'feather_falling': 2,
    'blast_protection': 3,
    'projectile_protection': 4,
    'respiration': 5,
    'aqua_affinity': 6,
    'thorns': 7,
    'depth_strider': 8,
    'sharpness': 16,
    'smite': 17,
    'bane_of_arthropods': 18,
    'knockback': 19,
    'fire_aspect': 20,
    'looting': 21,
    'efficiency': 32,
    'silk_touch': 33,
    'unbreaking': 34,
    'fortune': 35,
    'power': 48,
    'punch': 49,
    'flame': 50,
    'infinity': 51,
    'luck_of_the_sea': 61,
    'lure': 62,
}


INVENTORY_SLOTS = Literal[
    'first_slot',
    'hand_slot',
    'hotbar_slot_1',
    'hotbar_slot_2',
    'hotbar_slot_3',
    'hotbar_slot_4',
    'hotbar_slot_5',
    'hotbar_slot_6',
    'hotbar_slot_7',
    'hotbar_slot_8',
    'hotbar_slot_9',
    'inventory_slot_1',
    'inventory_slot_2',
    'inventory_slot_3',
    'inventory_slot_4',
    'inventory_slot_5',
    'inventory_slot_6',
    'inventory_slot_7',
    'inventory_slot_8',
    'inventory_slot_9',
    'inventory_slot_10',
    'inventory_slot_11',
    'inventory_slot_12',
    'inventory_slot_13',
    'inventory_slot_14',
    'inventory_slot_15',
    'inventory_slot_16',
    'inventory_slot_17',
    'inventory_slot_18',
    'inventory_slot_19',
    'inventory_slot_20',
    'inventory_slot_21',
    'inventory_slot_22',
    'inventory_slot_23',
    'inventory_slot_24',
    'inventory_slot_25',
    'inventory_slot_26',
    'inventory_slot_27',
    'helmet',
    'chestplate',
    'leggings',
    'boots',
]


NON_SPECIAL_ITEM_KEYS = Literal[
    'stone', 'granite', 'polished_granite', 'diorite', 'polished_diorite', 'andesite', 'polished_andesite', 'grass_block',
    'dirt', 'coarse_dirt', 'podzol', 'cobblestone', 'oak_planks', 'spruce_planks', 'birch_planks', 'jungle_planks',
    'acacia_planks', 'dark_oak_planks', 'oak_sapling', 'spruce_sapling', 'birch_sapling', 'jungle_sapling', 'acacia_sapling', 'dark_oak_sapling',
    'bedrock', 'sand', 'red_sand', 'gravel', 'gold_ore', 'iron_ore', 'coal_ore', 'oak_log',
    'spruce_log', 'birch_log', 'jungle_log', 'oak_leaves', 'spruce_leaves', 'birch_leaves', 'jungle_leaves', 'sponge',
    'wet_sponge', 'glass', 'lapis_lazuli_ore', 'lapis_lazuli_block', 'dispenser', 'sandstone', 'chiseled_sandstone', 'smooth_sandstone',
    'note_block', 'powered_rails', 'detector_rails', 'sticky_piston', 'cobweb', 'grass', 'fern', 'dead_bush',
    'piston', 'white_wool', 'orange_wool', 'magenta_wool', 'light_blue_wool', 'yellow_wool', 'lime_wool', 'pink_wool',
    'gray_wool', 'light_gray_wool', 'cyan_wool', 'purple_wool', 'blue_wool', 'brown_wool', 'green_wool', 'red_wool',
    'black_wool', 'dandelion', 'poppy', 'blue_orchid', 'allium', 'azure_bluet', 'red_tulip', 'orange_tulip',
    'white_tulip', 'pink_tulip', 'oxeye_daisy', 'brown_mushroom', 'red_mushroom', 'block_of_gold', 'block_of_iron', 'stone_slab',
    'sandstone_slab', 'cobblestone_slab', 'brick_slab', 'stone_brick_slab', 'nether_brick_slab', 'quartz_slab', 'bricks', 'tnt',
    'bookshelf', 'mossy_cobblestone', 'obsidian', 'torch', 'monster_spawner', 'oak_stairs', 'chest', 'diamond_ore',
    'block_of_diamond', 'crafting_table', 'farmland', 'furnace', 'ladder', 'rails', 'cobblestone_stairs', 'lever',
    'stone_pressure_plate', 'oak_pressure_plate', 'redstone_ore', 'redstone_torch', 'stone_button', 'snow', 'ice', 'snow_block',
    'cactus', 'clay_block', 'jukebox', 'oak_fence', 'pumpkin', 'netherrack', 'soul_sand', 'glowstone',
    'jack_o_lantern', 'white_stained_glass', 'orange_stained_glass', 'magenta_stained_glass', 'light_blue_stained_glass', 'yellow_stained_glass', 'lime_stained_glass', 'pink_stained_glass',
    'gray_stained_glass', 'light_gray_stained_glass', 'cyan_stained_glass', 'purple_stained_glass', 'blue_stained_glass', 'brown_stained_glass', 'green_stained_glass', 'red_stained_glass',
    'black_stained_glass', 'oak_trapdoor', 'infested_stone', 'infested_cobblestone', 'infested_stone_bricks', 'infested_mossy_stone_bricks', 'infested_cracked_stone_bricks', 'infested_chiseled_stone_bricks',
    'stone_bricks', 'mossy_stone_bricks', 'cracked_stone_bricks', 'chiseled_stone_bricks', 'brown_mushroom_block', 'red_mushroom_block', 'iron_bars', 'glass_pane',
    'block_of_melon', 'vines', 'oak_fence_gate', 'brick_stairs', 'stone_brick_stairs', 'mycelium', 'lily_pad', 'block_of_nether_bricks',
    'nether_brick_fence', 'nether_brick_stairs', 'enchanting_table', 'end_portal_frame', 'end_stone', 'dragon_egg', 'redstone_lamp', 'oak_slab',
    'spruce_slab', 'birch_slab', 'jungle_slab', 'acacia_slab', 'dark_oak_slab', 'sandstone_stairs', 'emerald_ore', 'ender_chest',
    'tripwire_hook', 'block_of_emerald', 'spruce_stairs', 'birch_stairs', 'jungle_stairs', 'command_block', 'beacon', 'cobblestone_wall',
    'mossy_cobblestone_wall', 'oak_button', 'anvil', 'slightly_damaged_anvil', 'very_damaged_anvil', 'trapped_chest', 'light_weighted_pressure_plate', 'heavy_weighted_pressure_plate',
    'daylight_detector', 'block_of_redstone', 'nether_quartz_ore', 'hopper', 'block_of_quartz', 'chiseled_quartz_block', 'quartz_pillar', 'quartz_stairs',
    'activator_rails', 'dropper', 'white_terracotta', 'orange_terracotta', 'magenta_terracotta', 'light_blue_terracotta', 'yellow_terracotta', 'lime_terracotta',
    'pink_terracotta', 'gray_terracotta', 'light_gray_terracotta', 'cyan_terracotta', 'purple_terracotta', 'blue_terracotta', 'brown_terracotta', 'green_terracotta',
    'red_terracotta', 'black_terracotta', 'white_stained_glass_pane', 'orange_stained_glass_pane', 'magenta_stained_glass_pane', 'light_blue_stained_glass_pane', 'yellow_stained_glass_pane', 'lime_stained_glass_pane',
    'pink_stained_glass_pane', 'gray_stained_glass_pane', 'light_gray_stained_glass_pane', 'cyan_stained_glass_pane', 'purple_stained_glass_pane', 'blue_stained_glass_pane', 'brown_stained_glass_pane', 'green_stained_glass_pane',
    'red_stained_glass_pane', 'black_stained_glass_pane', 'acacia_leaves', 'dark_oak_leaves', 'acacia_log', 'dark_oak_log', 'acacia_stairs', 'dark_oak_stairs',
    'slime_block', 'barrier', 'iron_trapdoor', 'prismarine', 'prismarine_bricks', 'dark_prismarine', 'sea_lantern', 'hay_bale',
    'white_carpet', 'orange_carpet', 'magenta_carpet', 'light_blue_carpet', 'yellow_carpet', 'lime_carpet', 'pink_carpet', 'gray_carpet',
    'light_gray_carpet', 'cyan_carpet', 'purple_carpet', 'blue_carpet', 'brown_carpet', 'green_carpet', 'red_carpet', 'black_carpet',
    'terracotta', 'coal_block', 'packed_ice', 'sunflower', 'lilac', 'tall_grass', 'large_fern', 'rose_bush',
    'peony', 'red_sandstone', 'chiseled_red_sandstone', 'smooth_red_sandstone', 'red_sandstone_stairs', 'red_sandstone_slab', 'spruce_fence_gate', 'birch_fence_gate',
    'jungle_fence_gate', 'dark_oak_fence_gate', 'acacia_fence_gate', 'spruce_fence', 'birch_fence', 'jungle_fence', 'dark_oak_fence', 'acacia_fence',
    'apple', 'arrow', 'coal', 'charcoal', 'diamond', 'iron_ingot', 'gold_ingot', 'stick',
    'bowl', 'mushroom_stew', 'string', 'feather', 'gunpowder', 'seeds', 'wheat', 'bread',
    'flint', 'raw_porkchop', 'cooked_porkchop', 'painting', 'golden_apple', 'enchanted_golden_apple', 'oak_sign', 'oak_door',
    'bucket', 'water_bucket', 'lava_bucket', 'minecart', 'saddle', 'iron_door', 'redstone_dust', 'snowball',
    'oak_boat', 'leather', 'milk_bucket', 'brick', 'clay_ball', 'sugar_canes', 'paper', 'book',
    'slimeball', 'minecart_with_chest', 'minecart_with_furnace', 'egg', 'compass', 'clock', 'glowstone_dust', 'raw_fish',
    'raw_salmon', 'clownfish', 'pufferfish', 'cooked_fish', 'cooked_salmon', 'ink_sac', 'red_dye', 'green_dye',
    'cocoa_beans', 'lapis_lazuli', 'purple_dye', 'cyan_dye', 'light_gray_dye', 'gray_dye', 'pink_dye', 'lime_dye',
    'yellow_dye', 'light_blue_dye', 'magenta_dye', 'orange_dye', 'bone_meal', 'bone', 'sugar', 'cake',
    'red_bed', 'redstone_repeater', 'cookie', 'filled_map', 'melon_slice', 'pumpkin_seeds', 'melon_seeds', 'raw_beef',
    'steak', 'raw_chicken', 'cooked_chicken', 'rotten_flesh', 'ender_pearl', 'blaze_rod', 'ghast_tear', 'gold_nugget',
    'nether_wart', 'water_bottle', 'potion_of_regeneration', 'potion_of_swiftness', 'potion_of_poison', 'potion_of_strength', 'potion_of_leaping', 'potion_of_regeneration_2',
    'potion_of_swiftness_2', 'potion_of_fire_resistance', 'potion_of_poison_2', 'potion_of_healing', 'potion_of_night_vision', 'potion_of_weakness', 'potion_of_strength_2', 'potion_of_slowness',
    'potion_of_leaping_2', 'potion_of_harming', 'potion_of_water_breathing', 'potion_of_invisibility', 'potion_of_regeneration_long', 'potion_of_swiftness_long', 'potion_of_fire_resistance_long', 'potion_of_poison_long',
    'potion_of_healing_long', 'potion_of_night_vision_long', 'potion_of_weakness_long', 'potion_of_strength_long', 'potion_of_slowness_long', 'potion_of_leaping_long', 'potion_of_harming_long', 'potion_of_water_breathing_long',
    'potion_of_invisibility_long', 'splash_potion_of_regeneration', 'splash_potion_of_swiftness', 'splash_potion_of_poison', 'splash_potion_of_strength', 'splash_potion_of_leaping', 'splash_potion_of_regeneration_2', 'splash_potion_of_swiftness_2',
    'splash_potion_of_fire_resistance', 'splash_potion_of_poison_2', 'splash_potion_of_healing', 'splash_potion_of_night_vision', 'splash_potion_of_weakness', 'splash_potion_of_strength_2', 'splash_potion_of_slowness', 'splash_potion_of_leaping_2',
    'splash_potion_of_harming', 'splash_potion_of_water_breathing', 'splash_potion_of_invisibility', 'splash_potion_of_regeneration_long', 'splash_potion_of_swiftness_long', 'splash_potion_of_fire_resistance_long', 'splash_potion_of_poison_long', 'splash_potion_of_healing_long',
    'splash_potion_of_night_vision_long', 'splash_potion_of_weakness_long', 'splash_potion_of_strength_long', 'splash_potion_of_slowness_long', 'splash_potion_of_leaping_long', 'splash_potion_of_harming_long', 'splash_potion_of_water_breathing_long', 'splash_potion_of_invisibility_long',
    'glass_bottle', 'spider_eye', 'fermented_spider_eye', 'blaze_powder', 'magma_cream', 'brewing_stand', 'cauldron', 'eye_of_ender',
    'glistering_melon_slice', 'creeper_spawn_egg', 'skeleton_spawn_egg', 'spider_spawn_egg', 'zombie_spawn_egg', 'slime_spawn_egg', 'ghast_spawn_egg', 'zombified_piglin_spawn_egg',
    'enderman_spawn_egg', 'cave_spider_spawn_egg', 'silverfish_spawn_egg', 'blaze_spawn_egg', 'magma_cube_spawn_egg', 'bat_spawn_egg', 'witch_spawn_egg', 'endermite_spawn_egg',
    'guardian_spawn_egg', 'pig_spawn_egg', 'sheep_spawn_egg', 'cow_spawn_egg', 'chicken_spawn_egg', 'squid_spawn_egg', 'wolf_spawn_egg', 'mooshroom_spawn_egg',
    'ocelot_spawn_egg', 'horse_spawn_egg', 'rabbit_spawn_egg', 'villager_spawn_egg', 'bottle_o_enchanting', 'fire_charge', 'book_and_quill', 'written_book',
    'emerald', 'item_frame', 'flower_pot', 'carrot', 'potato', 'baked_potato', 'poisonous_potato', 'map',
    'golden_carrot', 'skeleton_skull', 'wither_skeleton_skull', 'zombie_head', 'player_head', 'creeper_head', 'nether_star', 'pumpkin_pie',
    'firework_rocket', 'firework_star', 'enchanted_book', 'redstone_comparator', 'nether_brick', 'nether_quartz', 'minecart_with_tnt', 'minecart_with_hopper',
    'prismarine_shard', 'prismarine_crystals', 'raw_rabbit', 'cooked_rabbit', 'rabbit_stew', 'rabbits_foot', 'rabbit_hide', 'armor_stand',
    'iron_horse_armor', 'gold_horse_armor', 'diamond_horse_armor', 'lead', 'name_tag', 'minecart_with_command_block', 'raw_mutton', 'cooked_mutton',
    'black_banner', 'red_banner', 'green_banner', 'brown_banner', 'blue_banner', 'purple_banner', 'cyan_banner', 'light_gray_banner',
    'gray_banner', 'pink_banner', 'lime_banner', 'yellow_banner', 'light_blue_banner', 'magenta_banner', 'orange_banner', 'white_banner',
    'spruce_door', 'birch_door', 'jungle_door', 'acacia_door', 'dark_oak_door', 'music_disc_13', 'music_disc_cat', 'music_disc_blocks',
    'music_disc_chirp', 'music_disc_far', 'music_disc_mall', 'music_disc_mellohi', 'music_disc_stal', 'music_disc_strad', 'music_disc_ward', 'music_disc_11',
    'music_disc_wait',
]


DAMAGEABLE_ITEM_KEYS = Literal[
    'iron_shovel', 'iron_pickaxe', 'iron_axe', 'flint_and_steel', 'bow', 'iron_sword', 'wooden_sword', 'wooden_shovel',
    'wooden_pickaxe', 'wooden_axe', 'stone_sword', 'stone_shovel', 'stone_pickaxe', 'stone_axe', 'diamond_sword', 'diamond_shovel',
    'diamond_pickaxe', 'diamond_axe', 'golden_sword', 'golden_shovel', 'golden_pickaxe', 'golden_axe', 'wooden_hoe', 'stone_hoe',
    'iron_hoe', 'diamond_hoe', 'golden_hoe', 'chain_helmet', 'chain_chestplate', 'chain_leggings', 'chain_boots', 'iron_helmet',
    'iron_chestplate', 'iron_leggings', 'iron_boots', 'diamond_helmet', 'diamond_chestplate', 'diamond_leggings', 'diamond_boots', 'golden_helmet',
    'golden_chestplate', 'golden_leggings', 'golden_boots', 'fishing_rod', 'shears', 'carrot_on_a_stick',
]


LEATHER_ARMOR_KEYS = Literal[
    'leather_cap', 'leather_tunic', 'leather_pants', 'leather_boots',
]


ALL_POSSIBLE_ITEM_KEYS = NON_SPECIAL_ITEM_KEYS | DAMAGEABLE_ITEM_KEYS | LEATHER_ARMOR_KEYS


LOCATIONS = Literal[
    'house_spawn',
    'current_location',
    'invokers_location',
    'custom_coordinates',
]
